### ISSUE TITLE
Enforce 2 space for indentation

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#126]
Figure out how to indent sections and setting using 2 spaces instead of user-defined indentation setting. Plugin setting, other options...

**Comment by kirmanak** [comment]
@rodionos I offer add to the README an instruction on how to set up the indentation and a recommendation about its size. Force a user to use this particular indentation does not seem right, VSCode offers flexibility, which we're about to destroy.

**Comment by rodionos** [comment]
None of the indentation options except 2 spaces work for our format. If the config is deeply nested, it's difficult to read and edit it with any setting other than 2 spaces. Research if there is a setting to control spacing just for our plugin/format.

**Comment by kirmanak** [comment]
Implemented in #143
