### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#132]
1) Standardize widget settings, e.g. same timespan (1 day). 
2) Use explicit units in settings, e.g. `update-interval = 10 second` instead of `update-interval = 10`.
3) Replace metric names with `metric-1`, entity names with `entity-1`.
4) When inserting snippets, prepend a line break if the active line has characters other than whitespace. Attempt to add appropriate indent.

![image](https://user-images.githubusercontent.com/2098022/43774915-770ae142-9a53-11e8-8a64-11cd7d43caa4.png)

5) Contextual naming in snippets. 

When inserting `for`, lookup the last declared collection name. If list ends with `s`, remove it from list name and use it instead of `item`. In the below example:

```
for server in servers
    
endfor
```

![image](https://user-images.githubusercontent.com/2098022/43774950-95da30be-9a53-11e8-8db6-ed5401a8a121.png)

6) Get rid of `w` prefix in snippet names: `pie` instead of `wpie`

7) Add snippets for detail, aggregated series, and series with tags.

8) Add `portal: 3x2` snippet with the following content:

```ls
[configuration]
  offset-right = 50
  width-units = 3
  height-units = 2

  timespan = 1 day

  [group]

    [widget]
      type = chart
      [series]
        entity = entity-1
        metric = metric-1

    [widget]
      type = chart
      [series]
        entity = entity-2
        metric = metric-2

    [widget]
      type = chart
      [series]
        entity = entity-3
        metric = metric-3

  [group]
    [widget]
      type = chart
      [series]
        entity = entity-4
        metric = metric-4

    [widget]
      type = chart
      [series]
        entity = entity-5
        metric = metric-5

    [widget]
      type = chart
      [series]
        entity = entity-6
        metric = metric-6
```

**Comment by kirmanak** [comment]
6. The purpose of `w` letter in snippets names is to move these snippets to the top of the completition suggestions list. If I get rid of `w`, then the word `pie` sometimes (when it was already used) will be higher than the snippet with same name. And if user wants to use the snippet, not just word `pie`, he has to scroll the list.

**Comment by kirmanak** [comment]
@rodionos I am sorry, could you please specify, how should look `detail series` snippet?
Also, did you mean this by `aggregate series` snippet?

```txt
[series]
  entity = entity-1
  metric = metric-1
  type = avg
```

**Comment by rodionos** [comment]
* detail

```
[series]
  entity = entity-1
  metric = metric-1
```

* averaged

```
[series]
  entity = entity-1
  metric = metric-1
  statistics = avg
  period = 15 minute
```

**Comment by kirmanak** [comment]
@rodionos Can you please checkout to [snippets](https://github.com/kirmanak/Axibase-Charts-Syntax/pull/133) branch and review the changes before I merge them?
One problem: currently `for loop` snippet is not present in `Command Palette`, because it is not a snippet any more, it is a `CompetionItem` and processed in a different from snippets way.

**Comment by rodionos** [comment]
We can keep it simple for now and have it all in master.

**Comment by kirmanak** [comment]
Added with #133
