### ISSUE TITLE
Validate derived series

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#146]
Calculated series (with value setting) do not have to have metric and entity settings.

```
    [series]
      alias = abc
      entity = e-1
      metric = m-1

    [series]
      value = value('abc')
```

![image](https://user-images.githubusercontent.com/2098022/43892060-9d8a3454-9bd3-11e8-8321-5b6b5a31b847.png)

**Comment by kirmanak** [comment]
Fixed in #153
