### ISSUE TITLE
Code highlight should take data type into account

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#147]
![image](https://user-images.githubusercontent.com/2098022/43892131-d0890088-9bd3-11e8-97e3-2b79af4e6524.png)

Format numbers, booleans, and strings with different styles.

**Comment by kirmanak** [comment]
@rodionos Currently, the most of VSCode themes highlight them with different colors. I can't provide support for all possible color themes unfortunately, because when I change highlighting in one theme, it brokes in another. I guess, default VSCode themes are in priority.

**Comment by kirmanak** [comment]
@rodionos Even TypeScript language extension developers (Microsoft company) highlight boolean values and numbers with the same colour in your theme:
![constants](https://user-images.githubusercontent.com/24299495/43898085-dca79fd8-9be6-11e8-9707-8e914dd74594.png)
