### ISSUE TITLE
If snippet too basic

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#158]
```
if condition
  //this is too basic and not clear how to access a variable inside the condition and inside the block
endif
```

I suggest to create multiple snippets for the `if` snippet with more useful text within:

* if-number
* if-text
* if-elseif

https://github.com/axibase/charts/blob/728d73b6ab4d5d67a6b2d76c9c901c2ed5d98a49/syntax/control-structure.md#if--elseif--else--endif

Search configs from apps for useful examples.

Same for `for` loop. It's not clear how to access the variable inside the loop: a) in text b) in `if`.

**Comment by kirmanak** [comment]
@rodionos I guess, snippets aren't supposed to be examples, they're supposed to be templates.

**Comment by kirmanak** [comment]
Changed these snippets in #186
