### ISSUE TITLE
Validator: raise error if setting is mentioned several times

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#163]
Some settings break things, when specified multiple times, for example:
```
  width-units = 1
  height-units = 2
  width-units = 1
  height-units = 2
```

I guess this applies to all numeric settings, with some exceptions. Booleans are probably affected as well?

```
display = true
display = true
```

The recommended approach is to not to specifically check only layout settings such as width-units, but apply a more generic test to catch misconfigurations due to multiple lines.

![image](https://user-images.githubusercontent.com/2098022/43945085-ca3a54a0-9c89-11e8-8bdf-e706bc2fa334.png)

**Comment by kirmanak** [comment]
@rodionos The error is already raised:
![repetition](https://user-images.githubusercontent.com/24299495/43945903-51febd52-9c8c-11e8-8bd8-73d2956d2a23.png)

**Comment by kirmanak** [comment]
Higlighted as error in #177
