### ISSUE TITLE
List of settings doesn't include settings with dash

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#164]
Why `rotate-ticks` is missing?

![image](https://user-images.githubusercontent.com/2098022/43945223-2a290852-9c8a-11e8-9f79-756f3ebfb712.png)

**Comment by kirmanak** [comment]
@rodionos I have no idea why `rotateticks` is missing in your completion list. I use one list for spelling check and for completion suggestions. If `rotate-ticks` is not highlighted as a misspelling in your case, it must be present in the completion list.
Furthermore, the item is present in my VSCode:
![rotate](https://user-images.githubusercontent.com/24299495/43945514-f58caa8a-9c8a-11e8-8bd2-e2f8993c3ee8.png)

**Comment by rodionos** [comment]
My version may be lagging behind or maybe is different in other regards. The correct way to handle such issues is to request information about the VScode environment (if it is to blame) and to request the plugin version. Which information do you need to troubleshoot it and how do I provide it (add instructions to readme).

**Comment by kirmanak** [comment]
@rodionos https://github.com/kirmanak/Axibase-Charts-Syntax#bug-reports

**Comment by rodionos** [comment]
![image](https://user-images.githubusercontent.com/2098022/43947619-42e932ac-9c91-11e8-9a29-161baf10b2c8.png)

```
$ cd ~/.vscode/extensions/axibase-charts && git rev-parse HEAD
72b6f8a9789b38bbd9abb9dc8009e7f439844d51
```

**Comment by kirmanak** [comment]
@rodionos Well, I made the screenshot with the absolutely same configuration. Can you send me the portal? 
![screenshot from 2018-08-10 11-40-14](https://user-images.githubusercontent.com/24299495/43947979-2a995dd4-9c92-11e8-9db7-1886e9de0510.png)

**Comment by rodionos** [comment]
![image](https://user-images.githubusercontent.com/2098022/43948315-29fdd85e-9c93-11e8-9764-f908337ac3cd.png)

```
[configuration]
  entities = helswgvml704
  width-units = 1
  height-units = 2
  widgets-per-row = 1
  step-line = false
  last-value-label = none
  legend-position = top
  label-format = meta.entity.label
  add-meta = true
  timespan = 1 day
  statistic = avg
  rotate-ticks = 0
  update-interval = 0
  server-aggregate = true

[group]

[widget]
type = chart
[series]
metric = os.disk.fs.percent_used
```

**Comment by kirmanak** [comment]
@rodionos The problem is not with the portal, the problem is with unsaved file. These completions (as well as validations, formatting) are provided by language server, but VSCode does not connect to it unless file is saved. I am not sure whether this is a bug or not.

**Comment by rodionos** [comment]
Research if the issue with unsaved files can be fixed.

**Comment by kirmanak** [comment]
@rodionos I don't think that it can be fixed. I've tried to use `Java Extension Pack` by Microsoft in an unsaved file and it didn't work either. Only static functional such as snippets or syntax highlighting is available. Validation and dynamic completion aren't available.

**Comment by rodionos** [comment]
Once we have a list of settings in #165 ready, can they be made available to unsaved files similar to snippets?

**Comment by kirmanak** [comment]
@rodionos Why `similar to snippets`? It is possible to made them snippets like `setting = something`. When #165  is ready, snippets can contain content based on their type like `display = true`

**Comment by kirmanak** [comment]
@rodionos I've made the list of snippets in #219.
