### ISSUE TITLE
Create a settings reference in JSON

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#165]
We need to document all settings, their normalized names, user-friendly names, data-types, descriptions, and default values for programmatic consumption.

Sample description for one setting:

```json
{
  "section": "configuration",
  "name": "widthunits",
  "displayName": "width-units",
  "type": "number",
  "defaultValue": 4,
  "constraints": {
    "minValue": 1
  },
  "multiLine": false,
  "category": "Layout",
  "description": "Splits the page horizontally into the specified number of units."
}
```

**Comment by rodionos** [comment]
1) For settings that allow specific set of settings, specify them in an enum as part of constraints.

```
"constraints": {
    "enum": ["top", "bottom", "left", "right", "none"]
  }
```

2) type could be "boolean", "string", "enum", "integer", "number".

3) Also, to specify if the field supports javascript, add:

```
"script": true
```

**Comment by VeselovAlex** [comment]
2. More types: "time interval"

4. If setting is scriptable, describe functions and variables, which we can use in scripts (except JS standard library and Web API). E.g.

**Comment by VeselovAlex** [comment]
Example for `replace-value`
```json
{
    "name": "replacevalue",
    "displayName": "replace-value",
    "script": true,
    "scriptArgs": [
        {
            "type": "number",
            "name": "value",
            "description": "Value of current point"
        },
        {
            "type": "integer",
            "name": "time",
            "description": "UNIX timestamp of current point"
        },
        {
            "type": "number",
            "nullable": true,
            "name": "previousValue",
            "description": "Value of previous point. Null if current point is the first"
        },
        {
            "type": "integer",
            "nullable": true,
            "name": "previousTime",
            "description": "UNIX timestamp of previous point. Null if current point is the first"
        }
    ]
}
```

**Comment by VeselovAlex** [comment]
Script should be an object, containing fields and return value description.
```json
{
    "name": "replacevalue",
    "displayName": "replace-value",
    "script": {
        "fields": [
            {
                "type": "number",
                "name": "value",
                "description": "Value of current point"
            },
            {
                "type": "integer",
                "name": "time",
                "description": "UNIX timestamp of current point"
            },
            {
                "type": "number",
                "nullable": true,
                "name": "previousValue",
                "description": "Value of previous point. Null if current point is the first"
            },
            {
                "type": "integer",
                "nullable": true,
                "name": "previousTime",
                "description": "UNIX timestamp of previous point. Null if current point is the first"
            }
        ],
        "returnValue": {
            "type": "number",
            "description": "Computed series value for current time"
        }
    }
}
```

**Comment by kirmanak** [comment]
I've written a [JSON scheme](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/json/server/src/dictionary.schema.json). Any suggestions, improvements, fixes?

**Comment by rodionos** [comment]
I would use two data types: "date" and "interval". For example, "end-time" setting is a "date", whereas "timespan" is an "interval". The "date" can be an ISO or local date string or a calendar expression,e.g. "current_hour".

**Comment by rodionos** [comment]
Instead of "time interval".

**Comment by kirmanak** [comment]
@rodionos I've generated [the JSON](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/json/server/src/dictionary.json). It contains name, display name and dummy values for the required fields (type, description, multi-line, default value).

**Comment by rodionos** [comment]
Proceed to verify the names manually, for example I don't think we have `add` setting. `ahead-time-span` to `ahead-timespan` as we commonly use timespan word without dash, etc. Use the chart [repo](https://github.com/axibase/charts) to verify that the setting exists.

**Comment by kirmanak** [comment]
@rodionos the repo does not contain `author`, `arcs`, `menu`, `description`, `dummy` settings.
Several setting have been removed, `time-span` is replaced with `timespan`.

**Comment by rodionos** [comment]
Add these settings to shared `[widget]` settings.

* author - User who created this configuration
* principal - User under whose identity this configuration will be displayed
* description - Portal description

All are optional strings. Are there examples with `arcs` setting in chartlab configs?

**Comment by kirmanak** [comment]
@rodionos No, I've found this setting in charts sources, not in configs. It is a boolean setting, handled by `ChordGraphWidget`

**Comment by rodionos** [comment]
Add `example` field to the schema. Proceed to fully populate the first 20 settings to validate if the schema works and provides sufficient fields. As discussed. It's better to keep description in an external file, and not in JSON format for readability.

**Comment by kirmanak** [comment]
@rodionos What is the purpose of the `example` field? We already have `defaultValue` field and `description`.

**Comment by kirmanak** [comment]
@rodionos The twentieth setting was right before `axis-label`, which is present only in charts sources, neither in the charts repo nor chartlab configs. 
I've populated the first 20 settings, removed `description` field, added `example` field and removed `multiLine` field from the templates (still present in schema)

**Comment by rodionos** [comment]
What does axis-label do? I'm not able to see any difference when I set it.

**Comment by rodionos** [comment]
It works the same as the usual `label` setting:

```
label = hello
```

Ignore axis-label from the list of settings.

**Comment by kirmanak** [comment]
@rodionos What do you mean by `ignore`? Treat as a normal setting? Also, what about the JSON? Should I change anything?

**Comment by rodionos** [comment]
Do not include `axis-label` into the list of settings in the JSON file.
It is a duplicate of simply `label`.

**Comment by kirmanak** [comment]
@rodionos [Added](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/08205c789abb03842a39c9677fb050b8847b5494/server/src/dictionary.json#L72) the `script` field to `audio-alert` setting, which contains the fields of the script.

**Comment by rodionos** [comment]
https://github.com/kirmanak/Axibase-Charts-Syntax/blob/json/server/src/dictionary.json#L33 - `s1` would be better since often alias is assigned to series, whereas the metric could be the same for multiple series.

Proceed to document remaining settings.

**Comment by kirmanak** [comment]
@rodionos @VeselovAlex I've merged [the JSON](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/master/server/src/dictionary.json). Currently, I don't have examples for `link-value`, `node-value`, `node-radiuses`, `palette`, `path`, `principal`, because I could not find them. Can either of you provide them, please?

**Comment by kirmanak** [comment]
@rodionos @VeselovAlex Also, I don't know the type of `palette` setting. I am not even sure whether it is supported or not. I don't know types of parameters which are provided to JavaScript settings such as `value`, `replace-value`, `range-select-end` and so on (all of the parameters are listed).

**Comment by rodionos** [comment]
Could you please search config examples from apps that I shared a while ago. Also, some useful examples and descriptions can be obtained by googling 'axibase replace-value', for example.

**Comment by kirmanak** [comment]
@rodionos I've searched examples there already, neither of the provided portals use these settings. 
About `replace-value`: I don't need a description or an example, I need the list of the parameters, such as `metric`, `entity`, `previous`, `series`, `movavg`. The value of a JavaScript setting is wrapped in a JS function. For example,

```txt
replace-value = value + 100
```

Is actually something like:

```txt
replace-value = function(metric, entity, tags, ..., series) {
 return value + 100;
}
```

I need the types of these parameters and, if some of them are functions, I need the arguments of these functions. I guess, @VeselovAlex can somehow extract it, I failed to do it.

**Comment by rodionos** [comment]
>  I don't need a description or an example, I need the list of the parameters,

We don't have this information in a readily available form. Hence - use best efforts to extract the list of available parameters by looking at examples and the source code. This applies to `replace-value` and to other settings.
