### ISSUE TITLE
Display deprecated warning for freemarker expressions

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#168]
We used to advise customers to use freemarker: https://axibase.com/products/axibase-time-series-database/visualization/freemarker/. Not anymore.

Display the following warning for any freemarker expression that starts with `<#list ` or `<#assign` 

```
Freemarker expressions are deprecated. Use a native collection: list, csv table, var object.
```

```
<#list switchsets as switchset>

[group]

[widget]
```

![image](https://user-images.githubusercontent.com/2098022/43953070-939c71dc-9ca0-11e8-951c-34e5adf87abf.png)

**Comment by kirmanak** [comment]
Provided by #180
