### ISSUE TITLE
Validator: display warning instead of error if list is already defined

### ISSUE THREAD

**Issue by rodionos** [kirmanak/Axibase-Charts-Syntax#169]
Our list can be redefined. Re-using the list is an anti-pattern but there is nothing wrong.
To double check, verify that when we declare the list the second time, the list of elements is fully replaced.

1) If the list of elements is the same, display an ERROR: `{name} with the same elements is already defined`.
2) If elements are different, display a warning `{name} is already defined`.

![image](https://user-images.githubusercontent.com/2098022/43953425-97fac87c-9ca1-11e8-88a8-f74f828fc5ef.png)

**Comment by kirmanak** [comment]
@rodionos What is the principal difference between these two cases? Already defined list is not an error no matter does it have same content or not. If this is allowed, I think, we can provide a warning in both cases. 
Additionally, to distinguish already defined list from a list with same name, we have to store contents of every list in the portal and then compare them. I can do that, but is it so important?
