### ISSUE TITLE
Password storage in preview

### ISSUE THREAD

**Issue by kirmanak** [kirmanak/Axibase-Charts-Syntax#200]
Problem: passwords are currently being stored in `/tmp/portal-{hash}` file in plain text.

**Comment by rodionos** [comment]
Wish list for Preview:

- User clicks on Icon (similar to markdown) in the toolbar menu
- If settings are empty, incomplete, or user is not authorized:
  - Form is displayed with connection parameters: protocol, host, port, username, password
  - Protocol, host, port, username are stored in settings each time form is completed.
  - Password must not be stored in any file. Instead it must be passed to server.

**Comment by kirmanak** [comment]
@rodionos After #203 nothing is being stored on the filesystem anymore. But I am still not sure are passwords safe or not. 
Now the flow is:
1) [Ask](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/814482056d90eb98db63d66ddd5283adfb2aebca/client/src/axibaseChartsProvider.ts#L66) the user to provide the password in input box
2) Store the password as [a field](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/814482056d90eb98db63d66ddd5283adfb2aebca/client/src/axibaseChartsProvider.ts#L9) in an object
3) [Add credentials](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/814482056d90eb98db63d66ddd5283adfb2aebca/client/src/axibaseChartsProvider.ts#L92) as plain text to the document content
4) [Insert](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/814482056d90eb98db63d66ddd5283adfb2aebca/client/src/axibaseChartsProvider.ts#L131) the document content into an HTML page
5) [Pass](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/814482056d90eb98db63d66ddd5283adfb2aebca/client/src/extension.ts#L58) it to `vscode.previewHtml` command (vscode see `previewUri` and look for a provider, which is registered [here](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/814482056d90eb98db63d66ddd5283adfb2aebca/client/src/extension.ts#L48))

Who can tell is it safe enough or not?

**Comment by kirmanak** [comment]
@rodionos After #207 password is being sent to the server only [once](https://github.com/kirmanak/Axibase-Charts-Syntax/blob/547940d0b6e9fcb46831f59401118cf56c656a1c/client/src/axibaseChartsProvider.ts#L174) to receive cookie, which is being used after that to get series data from the server. Cookie is stored as plain text in the html, which is passed to `vscode.previewHtml` command.
